groups:
  - name: ero_alerts
    rules:
      - alert: HighRequestLatency
        expr: rate(http_request_duration_seconds_sum{job="ero-api"}[5m]) / rate(http_request_duration_seconds_count{job="ero-api"}[5m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High request latency on {{ $labels.instance }}
          description: Request latency is above 500ms for 5 minutes

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="ero-api",status=~"5.."}[5m]) / rate(http_requests_total{job="ero-api"}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate on {{ $labels.instance }}
          description: Error rate is above 5% for 5 minutes

      - alert: HighCPUUsage
        expr: sum(rate(process_cpu_seconds_total{job="ero-api"}[5m])) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on {{ $labels.instance }}
          description: CPU usage is above 80% for 5 minutes

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="ero-api"} / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on {{ $labels.instance }}
          description: Memory usage is above 80% for 5 minutes

      - alert: MLModelPredictionLatency
        expr: rate(ml_model_prediction_duration_seconds_sum[5m]) / rate(ml_model_prediction_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High ML model prediction latency
          description: ML model predictions are taking longer than 1 second on average

      - alert: DatabaseConnectionErrors
        expr: rate(database_connection_errors_total[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Database connection errors detected
          description: There are database connection errors in the last 5 minutes 